Repository 42Taskmaster/taskmaster, pull requests merged in 2021-02, with the labels that each got.

#26 Use CSP pattern to avoid mutexs and data races
  .gitignore
  cmd/taskmasterd/config.go
  cmd/taskmasterd/http.go
  cmd/taskmasterd/main.go
  cmd/taskmasterd/process.go
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/process_machine.go
  cmd/taskmasterd/process_map.go
  cmd/taskmasterd/program.go
  cmd/taskmasterd/program_manager.go
  cmd/taskmasterd/program_map.go
  cmd/taskmasterd/program_task.go
  cmd/taskmasterd/signals.go
  cmd/taskmasterd/task.go
  cmd/taskmasterd/taskmasterd.go
  cmd/taskmasterd/yaml.go
  tests/launch-tests.sh
  tests/scenarios/hot-reload-total-new-config/hot-reload-total-new-config.strest.yml
  tests/scenarios/hot-reload-total-new-config/taskmaster-init.yaml
  tests/scenarios/hot-reload-update-program-config/hot-reload-update-program-config.strest.yml
  tests/scenarios/hot-reload-update-program-config/taskmaster-init.yaml
  tests/scenarios/infinite/infinite.strest.yml
Labels: enhancement, server

#24 Change lock file location
  .github/workflows/ci.yml
  cmd/taskmasterd/lock.go
  cmd/taskmasterd/lock_test.go
Labels: enhancement, server

#35 Kill processes gratefully when a shutdown request is handled
  README.md
  cmd/taskmasterd/http.go
  cmd/taskmasterd/main.go
  cmd/taskmasterd/program.go
  cmd/taskmasterd/task.go
  cmd/taskmasterd/taskmasterd.go
  taskmaster.yaml
Labels: enhancement, server

#37 fix: fixed data races by using copies of process and pointers of deadCh
  cmd/taskmasterd/process.go
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/program.go
  tests/launch-tests.sh
Labels: bug, server

#38 Overwrite configuration file when a new configuration is received
  cmd/taskmasterd/config.go
  cmd/taskmasterd/http.go
  cmd/taskmasterd/main.go
  tests/launch-tests.sh
Labels: enhancement, server

#39 Close Command stdout and stderr opened files
  cmd/taskmasterd/process.go
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/yaml.go
Labels: enhancement, server

#40 Get configuration file through REST API
  cmd/taskmasterd/http.go
Labels: enhancement, server

#42 feat: enabled cors for http api
  cmd/taskmasterd/http.go
Labels: enhancement, server

#45 Keep track of processes start and stop time and return it from the API
  cmd/taskmasterd/http.go
  cmd/taskmasterd/process.go
  cmd/taskmasterd/process_actions.go
Labels: enhancement

#47 Specify CORS allowed headers
  cmd/taskmasterd/http.go
Labels: enhancement

#49 Use CSP with RPC to access and modify Process fields
  cmd/taskmasterd/http.go
  cmd/taskmasterd/process.go
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/process_machine.go
  cmd/taskmasterd/program.go
  cmd/taskmasterd/task.go
  machine/machine.go
  parser/parser.go
Labels: bug

#51 Fix infinite restarts after backoff
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/process_machine.go
  machine/machine.go
Labels: bug

#55 Handle stopped and exited states correctly
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/process_machine.go
Labels: bug

#57 Set API response Content-Type header to JSON
  cmd/taskmasterd/http.go
Labels: bug

#56 Reach backoff state if the command could not be executed
  cmd/taskmasterd/process_actions.go
  cmd/taskmasterd/process_machine.go
  taskmaster.yaml
  tests/launch-tests.sh
  tests/scenarios/not-found-command/not-found-command.strest.yml
  tests/scenarios/not-found-command/taskmaster.yaml
  tests/scenarios/not-found-command/test.sh
Labels: bug

#60 Return an empty PID of process not currently running
  cmd/taskmasterd/http.go
  tests/scenarios/hot-reload-total-new-config/hot-reload-total-new-config.strest.yml
  tests/scenarios/hot-reload-update-program-config/hot-reload-update-program-config.strest.yml
  tests/scenarios/infinite/infinite.strest.yml
  tests/scenarios/not-found-command/not-found-command.strest.yml
Labels: enhancement

#59 Add route to create program from json
  cmd/taskmasterd/config.go
  cmd/taskmasterd/http.go
  cmd/taskmasterd/main.go
  cmd/taskmasterd/program.go
  cmd/taskmasterd/signals.go
  cmd/taskmasterd/task.go
  cmd/taskmasterd/taskmasterd.go
  cmd/taskmasterd/yaml.go
  taskmaster.yaml
  tests/launch-tests.sh
  tests/scenarios/create-program/create-program.strest.yml
  tests/scenarios/create-program/taskmaster.yaml
  tests/scenarios/create-program/test.sh
Labels: enhancement

#61 Create a route to get the program version
  cmd/taskmasterd/http.go
  cmd/taskmasterd/taskmasterd.go
  tests/launch-tests.sh
  tests/scenarios/version/taskmaster.yaml
  tests/scenarios/version/test.sh
  tests/scenarios/version/version.strest.yml
Labels: enhancement

#64 Create a route to refresh the configuration
  cmd/taskmasterd/http.go
Labels: enhancement

#67 refactor: refactored processes identifier with program name
  cmd/taskmasterd/program.go
Labels: enhancement
